//! Renders a `Prover.toml` for the `oprf_identity_anchor` (`anchor`) circuit's
//! `oprf_proofs: [OPRFProof; 5]` parameter (`utils::types::OPRFProof { pk, dlog_e, dlog_s,
//! response_blinded, response, beta }`) from this crate's simulated committee output.
//!
//! TOML array-of-structs-with-a-nested-struct-field syntax was verified empirically before
//! use here (a throwaway `nargo` package in this session's scratchpad, discarded — see the
//! changelog entry this crate ships with) rather than assumed: `[[oprf_proofs]]` starts each
//! array element, and `[oprf_proofs.pk]` / `[oprf_proofs.response_blinded]` /
//! `[oprf_proofs.response]` (singular brackets — they are themselves plain structs, not
//! arrays) attach to the most recently started element.

use crate::babyjubjub::Point;
use crate::oprf::CommitteeEvaluation;
use ark_bn254::Fr;
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;
use std::fmt::Write as _;

fn field_to_dec(f: &Fr) -> String {
    let bytes = f.into_bigint().to_bytes_be();
    BigUint::from_bytes_be(&bytes).to_string()
}

fn biguint_to_dec(x: &BigUint) -> String {
    x.to_string()
}

fn point_table(out: &mut String, name: &str, p: &Point) {
    let _ = writeln!(out, "[{name}]");
    let _ = writeln!(out, "x = \"{}\"", field_to_dec(&p.x));
    let _ = writeln!(out, "y = \"{}\"", field_to_dec(&p.y));
}

/// One assembled `OPRFProof` witness, ready to render: the committee's evaluation plus the
/// client's own `beta` and unblinded `response` (the client, not the committee, holds
/// these — see `oprf::unblind`).
pub struct OprfProofWitness {
    pub pk: Point,
    pub dlog_e: Fr,
    pub dlog_s: Fr,
    pub response_blinded: Point,
    pub response: Point,
    pub beta: BigUint,
}

impl OprfProofWitness {
    pub fn from_evaluation(eval: &CommitteeEvaluation, response: Point, beta: BigUint) -> Self {
        OprfProofWitness {
            pk: eval.pk,
            dlog_e: eval.dlog_e,
            dlog_s: eval.dlog_s,
            response_blinded: eval.response_blinded,
            response,
            beta,
        }
    }

    fn render(&self) -> String {
        let mut out = String::new();
        let _ = writeln!(out, "[[oprf_proofs]]");
        let _ = writeln!(out, "dlog_e = \"{}\"", field_to_dec(&self.dlog_e));
        let _ = writeln!(out, "dlog_s = \"{}\"", field_to_dec(&self.dlog_s));
        let _ = writeln!(out, "beta = \"{}\"", biguint_to_dec(&self.beta));
        point_table(&mut out, "oprf_proofs.pk", &self.pk);
        point_table(&mut out, "oprf_proofs.response_blinded", &self.response_blinded);
        point_table(&mut out, "oprf_proofs.response", &self.response);
        out
    }
}

/// The `anchor` circuit's non-OPRF inputs, reusing exactly the same fixture
/// `query/src/main.nr`'s own `tests::fixture()` and `query/Prover.toml` already use, so the
/// `comm_in`/`identity_input` this crate derives its blinded query from is the one those
/// files already document (not a fresh, undocumented fixture).
pub struct AnchorFixture {
    pub comm_in: String,
    pub scheme_version: String,
}

/// Renders the full `Prover.toml` for `oprf_identity_anchor` given 5 assembled proofs.
pub fn render_anchor_prover_toml(fixture: &AnchorFixture, proofs: &[OprfProofWitness; 5]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by oprf-committee-dev (DEV-ONLY simulator).");
    let _ = writeln!(out, "# See oprf-committee-dev/README.md before trusting this for anything beyond");
    let _ = writeln!(out, "# local dev/test proving. Salted-value fixture matches");
    let _ = writeln!(out, "# circuits/oprf-identity-anchor/query/Prover.toml and query/src/main.nr's");
    let _ = writeln!(out, "# tests::fixture() exactly (same SAMPLE_DG1/salt/comm_in), so this Prover.toml");
    let _ = writeln!(out, "# derives the identical identity_input the query circuit's own committed fixture does.");
    let _ = writeln!(out);
    let _ = writeln!(out, "comm_in = \"{}\"", fixture.comm_in);
    let _ = writeln!(out, "scheme_version = \"{}\"", fixture.scheme_version);
    let _ = writeln!(out);
    let _ = writeln!(out, "[salted_dg1]");
    let _ = writeln!(out, "salt = \"1111\"");
    let _ = writeln!(out, "hash = \"0\"");
    let _ = writeln!(out, "value = [\"97\", \"91\", \"95\", \"31\", \"88\", \"80\", \"60\", \"65\", \"85\", \"83\", \"83\", \"73\", \"76\", \"86\", \"69\", \"82\", \"72\", \"65\", \"78\", \"68\", \"60\", \"60\", \"74\", \"79\", \"72\", \"78\", \"78\", \"89\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"80\", \"65\", \"49\", \"50\", \"51\", \"52\", \"53\", \"54\", \"55\", \"95\", \"65\", \"85\", \"83\", \"56\", \"56\", \"49\", \"49\", \"49\", \"50\", \"95\", \"77\", \"51\", \"48\", \"48\", \"49\", \"48\", \"49\", \"95\", \"60\", \"67\", \"89\", \"66\", \"69\", \"82\", \"67\", \"73\", \"84\", \"89\", \"60\", \"60\", \"60\", \"60\", \"60\", \"60\", \"0\", \"0\"]");
    let _ = writeln!(out);
    let _ = writeln!(out, "[salted_expiry_date]");
    let _ = writeln!(out, "salt = \"2222\"");
    let _ = writeln!(out, "hash = \"0\"");
    let _ = writeln!(out, "value = [\"51\", \"48\", \"48\", \"49\", \"48\", \"49\"]");
    let _ = writeln!(out);
    let _ = writeln!(out, "[salted_dg2_hash]");
    let _ = writeln!(out, "salt = \"3333\"");
    let _ = writeln!(out, "hash = \"0\"");
    let _ = writeln!(out, "value = \"4444\"");
    let _ = writeln!(out);
    let _ = writeln!(out, "[salted_dg2_hash_type]");
    let _ = writeln!(out, "salt = \"5555\"");
    let _ = writeln!(out, "hash = \"0\"");
    let _ = writeln!(out, "value = \"3\"");
    let _ = writeln!(out);
    let _ = writeln!(out, "[salted_private_nullifier]");
    let _ = writeln!(out, "salt = \"0\"");
    let _ = writeln!(out, "hash = \"6666\"");
    let _ = writeln!(out, "value = \"0\"");
    let _ = writeln!(out);

    for proof in proofs {
        out.push_str(&proof.render());
        out.push('\n');
    }

    out
}
