/**
 * The real `CommitteeCrypto` implementation — loads and calls the actual
 * BabyJubJub/Poseidon2/Chaum-Pedersen crypto core from `oprf-committee-dev/src/ffi.rs`,
 * closing the gap `CommitteeCrypto.ts`'s doc comment describes ("still stubbed here
 * specifically: loading and calling the real .wasm artifact from React Native").
 *
 * # Why this isn't a `WebAssembly.instantiate(...)` call
 *
 * React Native 0.74 (this app's pinned version — see `package.json`) defaults to the
 * Hermes JS engine, and Hermes has never implemented the `WebAssembly` global —
 * unresolved for years at https://github.com/facebook/hermes/issues/429; the first real
 * Hermes Wasm work landed in RN 0.84, six minor versions past what this app is on, so it
 * doesn't help here. The other RN-supported engine, JSC, was checked too and rejected:
 * JSC's WebAssembly implementation needs JIT to run, Apple disallows third-party JIT on
 * iOS (confirmed by the existence of Callstack's `polygen` project, built specifically
 * to route around this by ahead-of-time-compiling wasm with `wasm2c` rather than relying
 * on JSC's JIT'd Wasm path), and `jsc-android` explicitly disables its own WebAssembly
 * support outright — so switching `jsEngine` to `"jsc"` would not have produced a
 * working `WebAssembly` on either platform this app targets, only a partially-working
 * one on iOS device (not simulator) and a non-working one on Android.
 *
 * The actual approach here is the same *idea* `polygen` uses — ahead-of-time-compile the
 * wasm module into something the engine can already run, instead of depending on the
 * engine's own Wasm support — but simpler for this module's needs: Binaryen's `wasm2js`
 * transpiles the compiled `.wasm` binary into plain ES-module JavaScript at BUILD time
 * (see `scripts/build-wasm-core.sh`). `./generated/oprfCommitteeCore.js` is that output —
 * ordinary arithmetic/typed-array JS with no `WebAssembly.*` calls anywhere in it, so it
 * runs unmodified on Hermes (this app), JSC, V8, or Node (Jest), with zero engine-level
 * Wasm support required. `wasm2js` is a real, long-standing Binaryen tool (originally
 * built to polyfill WebAssembly for engines that predate it, e.g. old Safari/IE11), not
 * something invented for this task.
 *
 * # Correctness
 *
 * The generated JS is asserted byte-identical to the real Rust `ffi::evaluate_query` on
 * `ffi.rs`'s own `sample_input()` fixture in `CommitteeCrypto.test.ts` — the same
 * ground-truth vector `oprf-committee-dev/src/ffi.rs`'s
 * `evaluate_query_matches_direct_native_call` test checks against, generated by running
 * that fixture through the real crate (see this repo's changelog #084 for exactly how
 * that ground truth was extracted). That test is the strongest correctness check
 * available without a real device — **what has NOT been verified is this file actually
 * running inside a Hermes VM on a real phone**; only Node-under-Jest is exercised in
 * this environment (no Android/iOS device, emulator, or simulator here — see changelog
 * #084).
 */
import * as core from './generated/oprfCommitteeCore';
import type {
  CommitteeCrypto,
  OprfEvaluationResult,
  OprfRound1Commitment,
  OprfRound2Response,
} from './CommitteeCrypto';

/** `sk || b_q.x || b_q.y || ds_dlog || seed`, each field 32 bytes. Must match
 * `oprf-committee-dev/src/ffi.rs::INPUT_LEN`. */
const INPUT_LEN = 160;
/** `pk.x/y || dlog_e/dlog_s || response_blinded.x/y`, each field 32 bytes. Must match
 * `oprf-committee-dev/src/ffi.rs::OUTPUT_LEN`. */
const OUTPUT_LEN = 192;
const FIELD_LEN = 32;

/** `sk || b_q.x || b_q.y || seed`, each field 32 bytes. Must match
 * `oprf-committee-dev/src/ffi.rs::ROUND1_INPUT_LEN`. No `ds_dlog` field — round 1
 * computes no proof yet. */
const ROUND1_INPUT_LEN = 128;
/** `r_i.x/y || d_g.x/y || d_q.x/y || e_g.x/y || e_q.x/y` — five points. Must match
 * `oprf-committee-dev/src/ffi.rs::ROUND1_OUTPUT_LEN`. */
const ROUND1_OUTPUT_LEN = 320;
/** `sk || seed || rho_i || lambda_i || e`, each field 32 bytes. Must match
 * `oprf-committee-dev/src/ffi.rs::ROUND2_INPUT_LEN`. */
const ROUND2_INPUT_LEN = 160;
/** `z_i` — one big-endian BN254 `Fr`. Must match
 * `oprf-committee-dev/src/ffi.rs::ROUND2_OUTPUT_LEN`. */
const ROUND2_OUTPUT_LEN = 32;

/**
 * `DS_DLOG` — ASCII "DLOG Equality Proof" read as a big-endian integer. Copied
 * byte-for-byte from `committee-node/src/wasm_host.rs::DS_DLOG_BE` (itself independently
 * reconciled there against `circuits/oprf-identity-anchor/lib/identity-anchor/
 * src/lib.nr`'s `DS_DLOG` constant) — kept in lockstep by hand across the two hosts, the
 * same way this app already keeps `NUM_COMMITTEES` in lockstep with `mobile/`'s copy.
 * **Public, not secret** — safe to hardcode; every committee host and every proving
 * circuit in this repo must agree on this exact value or proofs won't verify.
 */
const DS_DLOG_BE = new Uint8Array([
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x4c, 0x4f,
  0x47, 0x20, 0x45, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x20, 0x50, 0x72, 0x6f, 0x6f, 0x66,
]);

/**
 * Mirrors `oprf-committee-dev/src/ffi.rs`'s `ERR_*` constants, for a human-readable
 * error rather than a bare negative number when one of the module's exports rejects an
 * input. Shared by `oprf_evaluate_query`, `oprf_round1`, and `oprf_round2_response` —
 * confirmed against `ffi.rs`: the threshold round functions introduce no new error
 * codes, they return the same five. The two length messages therefore can't name a
 * single expected length any more (it depends which export was called); callers pass
 * `exportName` to say which one.
 */
function describeErrorCode(code: number, exportName: string): string {
  switch (code) {
    case -1:
      return `ERR_BAD_INPUT_LEN — input was not the exact length ${exportName} expects (oprf_evaluate_query: 160, oprf_round1: 128, oprf_round2_response: 160)`;
    case -2:
      return `ERR_BAD_OUTPUT_LEN — output buffer was not the exact length ${exportName} expects (oprf_evaluate_query: 192, oprf_round1: 320, oprf_round2_response: 32)`;
    case -3:
      return 'ERR_ZERO_SECRET_KEY — this member\'s configured OPRF secret key/share is all-zero';
    case -4:
      return 'ERR_BLINDED_QUERY_NOT_ON_CURVE — the blinded query point is malformed';
    case -5:
      return 'ERR_BLINDED_QUERY_NOT_IN_SUBGROUP — blinded query is on-curve but outside the prime-order subgroup';
    default:
      return "unrecognized error code — oprf-committee-dev/src/ffi.rs's ERR_* constants may have changed";
  }
}

/**
 * Builds the fixed 160-byte wire-format input: `sk` (left-padded to 32 bytes) ||
 * `blindedQuery` (already 64 bytes) || `DS_DLOG_BE` || `seed`. Exported for
 * {@link CommitteeCrypto.test.ts}'s own marshaling check; not otherwise meant to be
 * called from outside this module.
 */
export function buildOprfInput(
  secretKeyBytes: Uint8Array,
  blindedQuery: Uint8Array,
  seed: Uint8Array,
): Uint8Array {
  if (secretKeyBytes.length > FIELD_LEN) {
    throw new RangeError(
      `buildOprfInput: secretKeyBytes is ${secretKeyBytes.length} bytes, expected at most ${FIELD_LEN} (big-endian BN254 Fr)`,
    );
  }
  if (blindedQuery.length !== 2 * FIELD_LEN) {
    throw new RangeError(
      `buildOprfInput: blindedQuery is ${blindedQuery.length} bytes, expected ${2 * FIELD_LEN}`,
    );
  }
  if (seed.length !== FIELD_LEN) {
    throw new RangeError(`buildOprfInput: seed is ${seed.length} bytes, expected ${FIELD_LEN}`);
  }

  const input = new Uint8Array(INPUT_LEN);
  input.set(secretKeyBytes, FIELD_LEN - secretKeyBytes.length); // left-pad sk into [0, 32)
  input.set(blindedQuery, FIELD_LEN); // [32, 96)
  input.set(DS_DLOG_BE, 3 * FIELD_LEN); // [96, 128)
  input.set(seed, 4 * FIELD_LEN); // [128, 160)
  return input;
}

/**
 * The synchronous, seed-taking core of the real implementation: marshals `input`
 * through the wasm2js-generated `oprf_alloc`/`oprf_evaluate_query`/`oprf_dealloc` calls
 * (the bare `wasm32-unknown-unknown` C-ABI pattern — no `wasm-bindgen` glue is present
 * in this build, matching `committee-node/src/wasm_host.rs`'s own marshaling) and
 * decodes the 192-byte output into an {@link OprfEvaluationResult}.
 *
 * Exported (rather than kept private) specifically so `CommitteeCrypto.test.ts` can
 * supply `oprf-committee-dev/src/ffi.rs`'s own fixed test seed and assert byte-identical
 * output against the real Rust computation — the public {@link wasmCommitteeCrypto}
 * below never calls this with anything but fresh CSPRNG bytes (see
 * `evaluateQueryWithFreshSeed`).
 */
export function evaluateQueryWithSeed(
  secretKeyBytes: Uint8Array,
  blindedQuery: Uint8Array,
  seed: Uint8Array,
): OprfEvaluationResult {
  const input = buildOprfInput(secretKeyBytes, blindedQuery, seed);

  const inputPtr = core.oprf_alloc(INPUT_LEN);
  const outputPtr = core.oprf_alloc(OUTPUT_LEN);
  try {
    // Re-read `core.memory.buffer` fresh right before every access rather than caching
    // a view across calls — wasm2js's simulated linear memory can replace its backing
    // `ArrayBuffer` on a grow (see `oprfCommitteeCore.d.ts`'s doc comment), which would
    // silently detach any view captured before that point.
    new Uint8Array(core.memory.buffer).set(input, inputPtr);

    const code = core.oprf_evaluate_query(inputPtr, INPUT_LEN, outputPtr, OUTPUT_LEN);
    if (code !== 0) {
      throw new Error(
        `oprf_evaluate_query returned error code ${code} (${describeErrorCode(code, 'oprf_evaluate_query')})`,
      );
    }

    const output = new Uint8Array(core.memory.buffer).slice(outputPtr, outputPtr + OUTPUT_LEN);
    return {
      pk: output.slice(0, 64),
      dlogProof: output.slice(64, 128),
      evaluation: output.slice(128, 192),
    };
  } finally {
    core.oprf_dealloc(inputPtr, INPUT_LEN);
    core.oprf_dealloc(outputPtr, OUTPUT_LEN);
  }
}

/**
 * Builds the fixed 128-byte `oprf_round1` wire-format input: `secretShareBytes`
 * (left-padded to 32 bytes) || `blindedQuery` (already 64 bytes) || `seed`. No
 * `DS_DLOG` field — round 1 computes no proof yet (see `ffi.rs::round1`'s doc comment).
 * Exported for {@link CommitteeCrypto.test.ts}'s own marshaling checks.
 */
export function buildRound1Input(
  secretShareBytes: Uint8Array,
  blindedQuery: Uint8Array,
  seed: Uint8Array,
): Uint8Array {
  if (secretShareBytes.length > FIELD_LEN) {
    throw new RangeError(
      `buildRound1Input: secretShareBytes is ${secretShareBytes.length} bytes, expected at most ${FIELD_LEN} (big-endian BN254 Fr)`,
    );
  }
  if (blindedQuery.length !== 2 * FIELD_LEN) {
    throw new RangeError(
      `buildRound1Input: blindedQuery is ${blindedQuery.length} bytes, expected ${2 * FIELD_LEN}`,
    );
  }
  if (seed.length !== FIELD_LEN) {
    throw new RangeError(`buildRound1Input: seed is ${seed.length} bytes, expected ${FIELD_LEN}`);
  }

  const input = new Uint8Array(ROUND1_INPUT_LEN);
  input.set(secretShareBytes, FIELD_LEN - secretShareBytes.length); // left-pad into [0, 32)
  input.set(blindedQuery, FIELD_LEN); // [32, 96)
  input.set(seed, 3 * FIELD_LEN); // [96, 128)
  return input;
}

/**
 * The synchronous core of threshold round 1: marshals through
 * `oprf_alloc`/`oprf_round1`/`oprf_dealloc` and decodes the 320-byte output (five
 * consecutive 64-byte BabyJubJub points, `ffi.rs::round1`'s write order) into an
 * {@link OprfRound1Commitment}. Exported for `CommitteeCrypto.test.ts`'s own fixture
 * checks; the public {@link wasmCommitteeCrypto} below wraps this with the
 * `CommitteeCrypto` interface unchanged (round 1's `seed` is always caller-supplied,
 * never generated in here — see `CommitteeCrypto.ts`'s doc comment on why).
 */
export function round1WithSeed(
  secretShareBytes: Uint8Array,
  blindedQuery: Uint8Array,
  seed: Uint8Array,
): OprfRound1Commitment {
  const input = buildRound1Input(secretShareBytes, blindedQuery, seed);

  const inputPtr = core.oprf_alloc(ROUND1_INPUT_LEN);
  const outputPtr = core.oprf_alloc(ROUND1_OUTPUT_LEN);
  try {
    new Uint8Array(core.memory.buffer).set(input, inputPtr);

    const code = core.oprf_round1(inputPtr, ROUND1_INPUT_LEN, outputPtr, ROUND1_OUTPUT_LEN);
    if (code !== 0) {
      throw new Error(`oprf_round1 returned error code ${code} (${describeErrorCode(code, 'oprf_round1')})`);
    }

    const output = new Uint8Array(core.memory.buffer).slice(outputPtr, outputPtr + ROUND1_OUTPUT_LEN);
    const point = (i: number) => output.slice(i * 64, (i + 1) * 64);
    return {
      rI: point(0),
      dG: point(1),
      dQ: point(2),
      eG: point(3),
      eQ: point(4),
    };
  } finally {
    core.oprf_dealloc(inputPtr, ROUND1_INPUT_LEN);
    core.oprf_dealloc(outputPtr, ROUND1_OUTPUT_LEN);
  }
}

/**
 * Builds the fixed 160-byte `oprf_round2_response` wire-format input:
 * `secretShareBytes` (left-padded to 32 bytes) || `seed` || `rhoI` || `lambdaI` || `e`.
 * `seed` must be byte-identical to the one given to the matching {@link
 * buildRound1Input}/`round1WithSeed` call for this query — see `CommitteeCrypto.ts`'s
 * doc comment. Exported for `CommitteeCrypto.test.ts`'s own marshaling checks.
 */
export function buildRound2Input(
  secretShareBytes: Uint8Array,
  seed: Uint8Array,
  rhoI: Uint8Array,
  lambdaI: Uint8Array,
  e: Uint8Array,
): Uint8Array {
  if (secretShareBytes.length > FIELD_LEN) {
    throw new RangeError(
      `buildRound2Input: secretShareBytes is ${secretShareBytes.length} bytes, expected at most ${FIELD_LEN} (big-endian BN254 Fr)`,
    );
  }
  for (const [name, value] of [
    ['seed', seed],
    ['rhoI', rhoI],
    ['lambdaI', lambdaI],
    ['e', e],
  ] as const) {
    if (value.length !== FIELD_LEN) {
      throw new RangeError(`buildRound2Input: ${name} is ${value.length} bytes, expected ${FIELD_LEN}`);
    }
  }

  const input = new Uint8Array(ROUND2_INPUT_LEN);
  input.set(secretShareBytes, FIELD_LEN - secretShareBytes.length); // left-pad into [0, 32)
  input.set(seed, FIELD_LEN); // [32, 64)
  input.set(rhoI, 2 * FIELD_LEN); // [64, 96)
  input.set(lambdaI, 3 * FIELD_LEN); // [96, 128)
  input.set(e, 4 * FIELD_LEN); // [128, 160)
  return input;
}

/**
 * The synchronous core of threshold round 2: marshals through
 * `oprf_alloc`/`oprf_round2_response`/`oprf_dealloc` and decodes the 32-byte output
 * (`z_i`) into an {@link OprfRound2Response}. Exported for `CommitteeCrypto.test.ts`'s
 * own fixture checks.
 */
export function round2ResponseWithSeed(
  secretShareBytes: Uint8Array,
  seed: Uint8Array,
  rhoI: Uint8Array,
  lambdaI: Uint8Array,
  e: Uint8Array,
): OprfRound2Response {
  const input = buildRound2Input(secretShareBytes, seed, rhoI, lambdaI, e);

  const inputPtr = core.oprf_alloc(ROUND2_INPUT_LEN);
  const outputPtr = core.oprf_alloc(ROUND2_OUTPUT_LEN);
  try {
    new Uint8Array(core.memory.buffer).set(input, inputPtr);

    const code = core.oprf_round2_response(inputPtr, ROUND2_INPUT_LEN, outputPtr, ROUND2_OUTPUT_LEN);
    if (code !== 0) {
      throw new Error(
        `oprf_round2_response returned error code ${code} (${describeErrorCode(code, 'oprf_round2_response')})`,
      );
    }

    const zI = new Uint8Array(core.memory.buffer).slice(outputPtr, outputPtr + ROUND2_OUTPUT_LEN);
    return { zI };
  } finally {
    core.oprf_dealloc(inputPtr, ROUND2_INPUT_LEN);
    core.oprf_dealloc(outputPtr, ROUND2_OUTPUT_LEN);
  }
}

/**
 * Sources 32 bytes of fresh randomness for the Chaum-Pedersen proof nonce via
 * `crypto.getRandomValues` — **never a fixed value in production**, exactly as
 * `oprf-committee-dev/src/ffi.rs`'s module doc warns (seed reuse across two calls leaks
 * the secret key, a classic Schnorr/Chaum-Pedersen nonce-reuse attack).
 *
 * This deliberately does NOT `import 'react-native-get-random-values'` itself — that
 * package's whole job is to install a global `crypto.getRandomValues` polyfill as a
 * side effect, and it must run exactly once, as early as possible, before any other
 * module that might need it (see `index.js`, which already imports it first, mirroring
 * `mobile/index.js`'s identical requirement). Importing it again here would be harmless
 * but misleading — it would suggest this module owns that responsibility when it
 * doesn't. Under Jest (`testEnvironment: 'node'`, no RN native modules available), this
 * relies instead on Node's own built-in `globalThis.crypto.getRandomValues` (available
 * since Node 20, confirmed present in this repo's Node version) — the same Web Crypto
 * API surface `react-native-get-random-values` polyfills for RN, so no test-only mock is
 * needed for this path either.
 */
function freshSeed(): Uint8Array {
  const seed = new Uint8Array(FIELD_LEN);
  const g = globalThis as { crypto?: Crypto };
  if (!g.crypto || typeof g.crypto.getRandomValues !== 'function') {
    throw new Error(
      'wasmCommitteeCrypto: global crypto.getRandomValues is not available — ' +
        "index.js must `import 'react-native-get-random-values'` before this module is used.",
    );
  }
  g.crypto.getRandomValues(seed);
  return seed;
}

/**
 * The real `CommitteeCrypto`. Install once at app startup via `setCommitteeCrypto`
 * (see `index.js`).
 *
 * `round1`/`round2Response` do NOT source their own randomness the way `evaluateQuery`
 * does — both take `seed` as a required parameter and pass it straight through to
 * {@link round1WithSeed}/{@link round2ResponseWithSeed}. This mirrors
 * `committee-node/src/wasm_host.rs`'s `CryptoCore::round1`/`round2_response`: the seed
 * must be identical across the two calls for one query, so the caller
 * (`chain/oprfCommittee.ts`, which persists it between rounds) has to own generating
 * and supplying it — this wrapper has no way to know which later `round2Response` call
 * belongs to a given `round1` call, so it cannot safely draw the randomness itself.
 */
export const wasmCommitteeCrypto: CommitteeCrypto = {
  async evaluateQuery(secretKeyBytes: Uint8Array, blindedQuery: Uint8Array): Promise<OprfEvaluationResult> {
    return evaluateQueryWithSeed(secretKeyBytes, blindedQuery, freshSeed());
  },
  async round1(
    secretShareBytes: Uint8Array,
    blindedQuery: Uint8Array,
    seed: Uint8Array,
  ): Promise<OprfRound1Commitment> {
    return round1WithSeed(secretShareBytes, blindedQuery, seed);
  },
  async round2Response(
    secretShareBytes: Uint8Array,
    seed: Uint8Array,
    rhoI: Uint8Array,
    lambdaI: Uint8Array,
    e: Uint8Array,
  ): Promise<OprfRound2Response> {
    return round2ResponseWithSeed(secretShareBytes, seed, rhoI, lambdaI, e);
  },
};

/**
 * Sources 32 bytes of fresh randomness the same way {@link freshSeed} does, exported
 * for callers outside this module that need to generate a round-1 seed themselves
 * (`chain/oprfCommittee.ts::submitRound1`, which must hold onto the value it draws in
 * order to replay it into round 2 — see this file's `wasmCommitteeCrypto` doc comment).
 */
export function freshOprfSeed(): Uint8Array {
  return freshSeed();
}
