[workspace]
members = [
    "query",
    "anchor",
    "disclosure",
    "migrate",
    "migrate-disclosure",
    "delegate-query",
    "delegate-persona",
    "lib/identity-anchor",
]
default-member = "anchor"
